### ISSUE TITLE
It does not work on non-English versions of steam

### ISSUE THREAD

**Issue by NuMeRoK** [colingg/SteamBulkKeyActivator#2]
How to fix:
1. Click "Steam" on the top left of steam
2. Click "Settings"
3. In appeared window click "Interface"
4. In language selection menu select "English"
5. Reload steam
6. ???
7. RROFIT

**Comment by dolaCmeo** [comment]
yeah, the way can fix most running problem 
but can't close the print Windows
I tried renamed the "print" into other language,but it doesn't work. :(

**Comment by NuMeRoK** [comment]
but prog still works :) 
it performs its main function. not so fast, but...
You can change name of this window in prog. at me it worked

**Comment by dolaCmeo** [comment]
maybe chinese is too difficult :)

**Comment by LeeOnell** [comment]
Hello,

A little trick for users from other countries, if you want the script SteamBulkKeyActivator.ahk working
with another language change some words at several lines.
Ex: English(Original file) to French:

steam_activate_window(){ ;activate the steam activation window
	WinWait, **Product Activation**, ;wait for the activation window to pop up
	IfWinNotActive, **Product Activation**, , WinActivate, **Product Activation**, ;if not active make active
	WinWaitActive, **Product Activation**, ;wait until active
========================================================================================================
steam_activate_window(){					;activate the steam activation window
	WinWait, **Activation de produit**, ;wait for the activation window to pop up
	IfWinNotActive, **Activation de produit**, , WinActivate, **Activation de produi**t, ;if not active make active
	WinWaitActive, **Activation de produit**, ;wait until active

####

is_print_window(){							;way to check if we have a new product or a duplicate
	applog("waiting 5 seconds for the print window to pop up")
	WinWait, **Print**,,5 ;wait 5 seconds.
	...
		IfWinNotActive, **Print**, WinActivate, **Print**,
		WinWaitActive, **Print**,
		WinKill,**Print**,
========================================================================================================
is_print_window(){							;way to check if we have a new product or a duplicate
	applog("waiting 5 seconds for the print window to pop up")
	WinWait, **Imprimer**,,5 ;wait 5 seconds.
	...
		IfWinNotActive, **Imprimer**, WinActivate, **Imprimer**,
		WinWaitActive, **Imprimer**,
		WinKill,**Imprimer**,

You must write the same words as displayed in the windows title of the Steam key windows and the print windows
