### ISSUE TITLE
Application hangs if product is already owned.

### ISSUE THREAD

**Issue by HiddenKn** [colingg/SteamBulkKeyActivator#4]
When you already own the product it doesn't continue.
I use this for my humble bundle to check if I didn't forget to activate some keys, but because of this bug I can't use it.

**Comment by 07416** [comment]
@HiddenKn Why did you close this issue?

**Comment by HiddenKn** [comment]
There was another comment that said that it couldn't be reproduced because the developer didn't have any DLC codes and I don't have any either. I don't know if the issue has been fixed so I guess I should have mentioned that, sorry.

**Comment by HiddenKn** [comment]
Ignore my last comment. I have no idea why this was closed or whether this is still a problem.
I don't have time to look into it at the moment though. Feel free to remove this issue and make a new one if the issue is still ongoing.
