### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by MagikGimp** [colingg/SteamBulkKeyActivator#7]
Since Valve changed Steam's layout this app no longer works but I should imagine only a quick fix would be necessary to get it working again. Any chance the code could be jiggled around a little? Since they also dropped the OAuth stuff, adding keys, from bundles especially, is a real pain now so SBKA could be a life-saver. Much appreciated if possible! Thank you.

**Comment by KevinWang15** [comment]
@MagikGimp I fixed it! Added some new features too. https://github.com/KevinWang15/SteamBulkKeyActivator

**Comment by colingg** [comment]
Fixed in #6

**Comment by MagikGimp** [comment]
Sorry this is my fault, I didn't fully understand where to find the various pulls / forks or whatever they're called. I did in the end find and use Vijay's build from the Arquade (StackExchange) thread [here](http://gaming.stackexchange.com/questions/107580/bulk-activate-product-keys-in-steam). At least I assume that's the same one as it uses AutoHotKey to compile.
Anyway, I've been through all my keys (that still work at least, damn you Russian thieves!) but should I buy more bundles in the future I'll be sure to check out your build too Kev. Cheers all!
